import Head from 'next/head'
const Header = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div className="container mx-auto p-4">
					<h1 className="text-center">Create Next App</h1>
				</div>
			</header>
		</>
	)
}
export default Header
